name: Gatsby PR build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Get latest npm version
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-optional
      - name: Validate AELIN & ACCP frontmatters
        run: npm test
